### ISSUE TITLE
Error when Electron dev console is open

### ISSUE THREAD

**Issue by kristofferR** [jonluca/Stream-Enhancer-Site#11]
Perhaps this is a direct consequence of #10, but the app just gets an error message window if launched directly by a streamenhancher:// link when directly launched or when the Electron dev console is still open.

<img width="1236" alt="skjermbilde 2019-03-07 kl 13 38 57" src="https://user-images.githubusercontent.com/481270/53957368-74529f80-40de-11e9-94c1-d1b60fcd95d2.png">

**Comment by jonluca** [comment]
Yeah I think it should be fixed.

So odd, not sure how that got in there. Thanks!
